### PR TITLE
solved 3 questions in list

### PR DESCRIPTION
**Pull request by nitya123-github**
Solved string is palindrome/not  , string is rotation/not, Kadanes algorithm in python

### CODE REVIEW

**Comment by nlok5923** [comment]
@nitya123-github thanks for pr . but please remember you must submit pr after you get assigned to issue.

Thank you.

**Comment by nlok5923** [comment]
@nitya123-github please update the python solution status table.

**Comment by nitya123-github** [comment]
okay. then is this not counted for dwoc?

**Comment by nitya123-github** [comment]
can i please know how to change the status in table?

**Comment by nlok5923** [comment]
You just need to replace ⭕ with ✅ .

**Comment by nitya123-github** [comment]
yeah i understood but i couldnt change in that table

**Comment by nlok5923** [comment]
Please pull the latest changes

**Pull request closed without merging**
